# EduAction - Body + Hands (65 keypoints)
# Body (0-22) + Left hand (91-111) + Right hand (112-132)

work_dir: ./work_dir/eduaction/mgsan_body_hands

feeder: feeders.feeder_eduaction.FeederEduAction
train_feeder_args:
  data_dir: /mnt/d/data/EduAction_pose_data
  split: train
  window_size: 64
  p_interval: [0.5, 1]
  random_rot: True
  debug: False
  train_ratio: 0.7
  seed: 42
  bone: False
  vel: False
  keypoint_subset: body_hands

test_feeder_args:
  data_dir: /mnt/d/data/EduAction_pose_data
  split: test
  window_size: 64
  p_interval: [1]
  random_rot: False
  debug: False
  train_ratio: 0.7
  seed: 42
  bone: False
  vel: False
  keypoint_subset: body_hands

model: model.MGSAN.Model
model_args:
  num_class: 7
  num_point: 65  # body_hands
  num_person: 1
  in_channels: 2
  graph: graph.eduaction.GraphEduActionBodyHands
  dropout: 0.1
  Is_joint: True
  K: 0
  graph_args:
    labeling_mode: 'spatial'

weight_decay: 0.0004
base_lr: 0.01
lr_decay_rate: 0.1
step: [60, 80, 100]
warm_up_epoch: 5

device: [0]
batch_size: 16
test_batch_size: 16
num_epoch: 120
num_worker: 4
nesterov: True
